In [1]:
from pylab import plt
plt.style.use('seaborn')
import matplotlib as mpl
mpl.rcParams['font.family'] = 'serif'
%matplotlib inline

In [2]:
def perf_comp_data(func_list, data_list, rep=3, number=1):
    ''' Function to compare the performance of different functions.
    
    Parameters
    ==========
    func_list : list
        list with function names as strings
    data_list : list
        list with data set names as strings
    rep : int
        number of repetitions of the whole comparison
    number : int
        number of executions for every function
    '''
    from timeit import repeat
    res_list = {}
    for name in enumerate(func_list):
        stmt = name[1] + '(' + data_list[name[0]] + ')'
        setup = "from __main__ import " + name[1] + ', ' \
                                    + data_list[name[0]]
        results = repeat(stmt=stmt, setup=setup,
                         repeat=rep, number=number)
        res_list[name[1]] = sum(results) / rep
    res_sort = sorted(res_list.items(),
                      key=lambda x: (x[1], x[0]))
    for item in res_sort:
        rel = item[1] / res_sort[0][1]
        print ('function: ' + item[0] +
              ', av. time sec: %9.5f, ' % item[1]
            + 'relative: %6.1f' % rel)

In [3]:
from math import *
def f(x):
    return abs(cos(x)) ** 0.5 + sin(2 + 3 * x)

In [4]:
I = 500000
a_py = range(I)

In [5]:
def f1(a):
    res = []
    for x in a:
        res.append(f(x))
    return res

In [6]:
def f2(a):
    return [f(x) for x in a]

In [7]:
def f3(a):
    ex = 'abs(cos(x)) ** 0.5 + sin(2 + 3 * x)'
    return [eval(ex) for x in a]

In [8]:
import numpy as np

In [9]:
a_np = np.arange(I)

In [10]:
def f4(a):
    return (np.abs(np.cos(a)) ** 0.5 +
            np.sin(2 + 3 * a))

In [11]:
import numexpr as ne

In [12]:
def f5(a):
    ex = 'abs(cos(a)) ** 0.5 + sin(2 + 3 * a)'
    ne.set_num_threads(1)
    return ne.evaluate(ex)

In [13]:
def f6(a):
    ex = 'abs(cos(a)) ** 0.5 + sin(2 + 3 * a)'
    ne.set_num_threads(16)
    return ne.evaluate(ex)

In [14]:
%%time
r1 = f1(a_py)
r2 = f2(a_py)
r3 = f3(a_py)
r4 = f4(a_np)
r5 = f5(a_np)
r6 = f6(a_np)

Wall time: 15.1 s


In [15]:
func_list = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6']
data_list = ['a_py', 'a_py', 'a_py', 'a_np', 'a_np', 'a_np']

In [16]:
perf_comp_data(func_list, data_list)

function: f6, av. time sec:   0.02622, relative:    1.0
function: f5, av. time sec:   0.06973, relative:    2.7
function: f4, av. time sec:   0.07142, relative:    2.7
function: f2, av. time sec:   0.67450, relative:   25.7
function: f1, av. time sec:   0.84083, relative:   32.1
function: f3, av. time sec:  13.71981, relative:  523.2


In [17]:
x = np.random.standard_normal((3, 150000))
C = np.array(x, order='C')
F = np.array(x, order='F')
x = 0.0

In [18]:
%timeit C.sum(axis=0)

1.83 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%timeit C.sum(axis=1)

817 µs ± 111 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%timeit C.std(axis=0)

7.78 ms ± 37 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%timeit C.std(axis=1)

4.48 ms ± 51 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
%timeit F.sum(axis=0)

4.5 ms ± 264 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%timeit F.sum(axis=1)

5.3 ms ± 32.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%timeit F.std(axis=0)

19.9 ms ± 611 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
%timeit F.std(axis=1)

15.7 ms ± 334 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
import multiprocessing as mp

In [27]:
import math
def simulate_geometric_brownian_motion(p):
    M, I = p
      # time steps, paths
    S0 = 100; r = 0.05; sigma = 0.2; T = 1.0
      # model parameters
    dt = T / M
    paths = np.zeros((M + 1, I))
    paths[0] = S0
    for t in range(1, M + 1):
        paths[t] = paths[t - 1] * np.exp((r - 0.5 * sigma ** 2) * dt +
                    sigma * math.sqrt(dt) * np.random.standard_normal(I))
    return paths

In [28]:
paths = simulate_geometric_brownian_motion((5, 2))
paths

array([[ 100.        ,  100.        ],
       [ 100.00062692,   96.8857298 ],
       [ 101.54287098,   93.02858348],
       [ 106.28428343,  106.92405511],
       [ 100.81123445,   91.9035519 ],
       [  88.4150375 ,  102.62149544]])

In [29]:
I = 10000  # number of paths
M = 50  # number of time steps
t = 20  # number of tasks/simulations

In [30]:
from math import cos, log
def f_py(I, J):
    res = 0
    for i in range(I):
        for j in range (J):
            res += int(cos(log(1)))
    return res

In [31]:
I, J = 2500, 2500
%time f_py(I, J)

Wall time: 5.38 s


6250000

In [32]:
def f_np(I, J):
    a = np.ones((I, J), dtype=np.float64)
    return int(np.sum(np.cos(np.log(a)))), a

In [33]:
%time res, a = f_np(I, J)

Wall time: 353 ms


In [34]:
a.nbytes

50000000

In [36]:
import numba as nb

In [37]:
f_nb = nb.jit(f_py)

In [38]:
%time f_nb(I, J)

Wall time: 483 ms


6250000

In [39]:
func_list = ['f_py', 'f_np', 'f_nb']
data_list = 3 * ['I, J']

In [40]:
perf_comp_data(func_list, data_list)

function: f_nb, av. time sec:   0.00000, relative:    1.0
function: f_np, av. time sec:   0.29764, relative: 190255.2
function: f_py, av. time sec:   5.05886, relative: 3233644.0


In [41]:
# model & option Parameters
S0 = 100.  # initial index level
T = 1.  # call option maturity
r = 0.05  # constant short rate
vola = 0.20  # constant volatility factor of diffusion

# time parameters
M = 1000  # time steps
dt = T / M  # length of time interval
df = exp(-r * dt)  # discount factor per time interval

# binomial parameters
u = exp(vola * sqrt(dt))  # up-movement
d = 1 / u  # down-movement
q = (exp(r * dt) - d) / (u - d)  # martingale probability

In [42]:
import numpy as np
def binomial_py(strike):
    ''' Binomial option pricing via looping.
    
    Parameters
    ==========
    strike : float
        strike price of the European call option
    '''
    # LOOP 1 - Index Levels
    S = np.zeros((M + 1, M + 1), dtype=np.float64)
      # index level array
    S[0, 0] = S0
    z1 = 0
    for j in range(1, M + 1, 1):
        z1 = z1 + 1
        for i in range(z1 + 1):
            S[i, j] = S[0, 0] * (u ** j) * (d ** (i * 2))
            
    # LOOP 2 - Inner Values
    iv = np.zeros((M + 1, M + 1), dtype=np.float64)
      # inner value array
    z2 = 0
    for j in range(0, M + 1, 1):
        for i in range(z2 + 1):
            iv[i, j] = max(S[i, j] - strike, 0)
        z2 = z2 + 1
        
    # LOOP 3 - Valuation
    pv = np.zeros((M + 1, M + 1), dtype=np.float64)
      # present value array
    pv[:, M] = iv[:, M]  # initialize last time point
    z3 = M + 1
    for j in range(M - 1, -1, -1):
        z3 = z3 - 1
        for i in range(z3):
            pv[i, j] = (q * pv[i, j + 1] +
                        (1 - q) * pv[i + 1, j + 1]) * df
    return pv[0, 0]

In [43]:
%time round(binomial_py(100), 3)

Wall time: 2.92 s


10.449

In [44]:
def binomial_np(strike):
    ''' Binomial option pricing with NumPy.
    
    Parameters
    ==========
    strike : float
        strike price of the European call option
    '''
    # Index Levels with NumPy
    mu = np.arange(M + 1)
    mu = np.resize(mu, (M + 1, M + 1))
    md = np.transpose(mu)
    mu = u ** (mu - md)
    md = d ** md
    S = S0 * mu * md
    
    # Valuation Loop
    pv = np.maximum(S - strike, 0)

    z = 0
    for t in range(M - 1, -1, -1):  # backwards iteration
        pv[0:M - z, t] = (q * pv[0:M - z, t + 1]
                        + (1 - q) * pv[1:M - z + 1, t + 1]) * df
        z += 1
    return pv[0, 0]

In [45]:
M = 4  # four time steps only
mu = np.arange(M + 1)
mu

array([0, 1, 2, 3, 4])

In [46]:
mu = np.resize(mu, (M + 1, M + 1))
mu

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [47]:
md = np.transpose(mu)
md

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [48]:
mu = u ** (mu - md)
mu.round(3)

array([[ 1.   ,  1.006,  1.013,  1.019,  1.026],
       [ 0.994,  1.   ,  1.006,  1.013,  1.019],
       [ 0.987,  0.994,  1.   ,  1.006,  1.013],
       [ 0.981,  0.987,  0.994,  1.   ,  1.006],
       [ 0.975,  0.981,  0.987,  0.994,  1.   ]])

In [49]:
md = d ** md
md.round(3)

array([[ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ],
       [ 0.994,  0.994,  0.994,  0.994,  0.994],
       [ 0.987,  0.987,  0.987,  0.987,  0.987],
       [ 0.981,  0.981,  0.981,  0.981,  0.981],
       [ 0.975,  0.975,  0.975,  0.975,  0.975]])

In [50]:
S = S0 * mu * md
S.round(3)

array([[ 100.   ,  100.634,  101.273,  101.915,  102.562],
       [  98.743,   99.37 ,  100.   ,  100.634,  101.273],
       [  97.502,   98.121,   98.743,   99.37 ,  100.   ],
       [  96.276,   96.887,   97.502,   98.121,   98.743],
       [  95.066,   95.669,   96.276,   96.887,   97.502]])

In [51]:
M = 1000  # reset number of time steps
%time round(binomial_np(100), 3)

Wall time: 234 ms


10.449

In [52]:
binomial_nb = nb.jit(binomial_py)

In [53]:
%time round(binomial_nb(100), 3)

Wall time: 849 ms


10.449

In [54]:
func_list = ['binomial_py', 'binomial_np', 'binomial_nb']
K = 100.
data_list = 3 * ['K']

In [55]:
perf_comp_data(func_list, data_list)

function: binomial_np, av. time sec:   0.18935, relative:    1.0
function: binomial_nb, av. time sec:   0.23121, relative:    1.2
function: binomial_py, av. time sec:   2.87990, relative:   15.2


In [56]:
def f_py(I, J):
    res = 0.  # we work on a float object
    for i in range(I):
        for j in range (J * I):
            res += 1
    return res

In [57]:
I, J = 500, 500
%time f_py(I, J)

Wall time: 27.6 s


125000000.0

In [58]:
import pyximport
pyximport.install()

(None, <pyximport.pyximport.PyxImporter at 0xf2b9890>)

In [61]:
import sys
sys.path.append('.')

In [63]:
%load_ext Cython